name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set Module Verion
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: version
          value: ${{ github.event.release.tag_name }}

      # Update Other Fields Here
      - name: Set Module Repository
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: url
          value: https://github.com/${{github.repository}}

      - name: Set Module Manifest
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: manifest
          value: https://github.com/${{github.repository}}/releases/latest/download/module.json
          
      - name: Set Module Download
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: download
          value: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip
          
      - name: Set Module Readme
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: readme
          value: "https://github.com/${{github.repository}}/blob/master/README.md"
          
      - name: Set Module ChangeLog
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: changelog
          value: "https://raw.githubusercontent.com/${{github.repository}}/master/CHANGELOG.md"
          
      - name: Set Module License
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: license
          value: "https://github.com/mouse0270/${{github.repository}}/blob/master/LICENSE"
          
      - name: Set Module Issues URL
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: bugs
          value: "https://github.com/${{github.repository}}/issues"

      - name: Disable Module Debug Logger
        uses: jossef/action-set-json-field@v2.1
        with:
          file: module.json
          field: flags.logger.enabled
          value: false
        
      - name: Create Release
        run: zip -r ./module.zip module.json LICENSE README.md CHANGELOG.md ATTRIBUTIONS.md dist/ languages/

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./module.zip
            module.json
        